name: release

on:
  release:
    types: 
      - published

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    uses: ./.github/workflows/build.yml

  upload-release-assets:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: KSPTextureLoader
          path: KSPTextureLoader
      - uses: actions/download-artifact@v4
        with:
          name: KSPTextureLoader.version
      - run: tree

      - name: Create Zip
        run: |
          cd KSPTextureLoader
          zip -r9 ../KSPTextureLoader.zip *

      - name: Upload Release Assets
        run: |
          gh release upload --clobber ${{ github.ref_name }}  \
            KSPTextureLoader.zip                  \
            KSPTextureLoader.version
